# -*- coding: utf-8 -*-
"""Reusable Android/Windows QR pairing dialog.

Flet's QR/camera scanner availability varies by runtime/build.  This dialog is
camera-ready when a scanner control exists, and always provides a paste fallback
for the QR payload generated by Windows.
"""
from __future__ import annotations

import inspect
import flet as ft
from views.flet_compat import open_control, close_control
from views.ui_kit import info_banner, show_snackbar


def _set_button_loading(button, text: str, loading: bool = True):
    try:
        button.disabled = loading
        if loading:
            button.content = ft.Row([ft.ProgressRing(width=16, height=16), ft.Text(text)], alignment=ft.MainAxisAlignment.CENTER)
    except Exception:
        pass


def open_qr_pairing_dialog(page: ft.Page, *, on_success=None, initial_text: str = ""):
    qr_field = ft.TextField(
        label="نص QR / رمز الربط",
        hint_text="الصق نص الربط الذي يولده Windows أو امسح QR بالكاميرا",
        value=initial_text or "",
        multiline=True,
        min_lines=4,
        max_lines=7,
        border_radius=14,
        text_size=12,
        text_align=ft.TextAlign.LEFT,
        rtl=False,
    )
    status = ft.Text("", size=12, color=ft.Colors.GREY_600, text_align=ft.TextAlign.CENTER)

    apply_btn = ft.FilledButton(
        content=ft.Row([ft.Icon(ft.Icons.LINK), ft.Text("ربط وحفظ")], alignment=ft.MainAxisAlignment.CENTER),
        bgcolor=ft.Colors.INDIGO,
        color=ft.Colors.WHITE,
    )

    def _apply_payload(payload: str):
        try:
            if not payload or not payload.strip():
                status.value = "الصق نص الربط أو امسح QR أولاً"
                status.color = ft.Colors.RED
                page.update()
                return
            _set_button_loading(apply_btn, "جاري الربط", True)
            status.value = "جاري فحص الخادم ورمز الربط..."
            status.color = ft.Colors.INDIGO
            page.update()
            from services.pairing_service import MobilePairingService
            result = MobilePairingService.pair_from_qr_text(payload)
            if not result.ok:
                status.value = result.message
                status.color = ft.Colors.RED
                return
            status.value = f"✅ {result.message}\n{result.server_name} — {result.server_url}"
            status.color = ft.Colors.GREEN
            show_snackbar(page, "تم ربط الهاتف بالخادم. سجّل الدخول بحسابك.", False)
            if callable(on_success):
                on_success(result)
            close_control(page, dlg)
        except Exception as ex:
            status.value = f"❌ فشل الربط: {ex}"
            status.color = ft.Colors.RED
        finally:
            try:
                apply_btn.disabled = False
                apply_btn.content = ft.Row([ft.Icon(ft.Icons.LINK), ft.Text("ربط وحفظ")], alignment=ft.MainAxisAlignment.CENTER)
                page.update()
            except Exception:
                pass

    def do_pair(ev):
        _apply_payload(qr_field.value or "")

    def paste_clipboard(ev):
        try:
            getter = getattr(page, "get_clipboard", None)
            if not callable(getter):
                status.value = "هذه نسخة Flet لا توفر قراءة الحافظة. الصق النص يدوياً."
                status.color = ft.Colors.ORANGE
                page.update()
                return
            value = getter()
            if inspect.iscoroutine(value):
                async def _await_clip():
                    try:
                        text = await value
                        qr_field.value = str(text or "")
                        status.value = "تم لصق نص الربط من الحافظة"
                        status.color = ft.Colors.GREEN
                        page.update()
                    except Exception as ex:
                        status.value = f"تعذر قراءة الحافظة: {ex}"
                        status.color = ft.Colors.RED
                        page.update()
                runner = getattr(page, "run_task", None)
                if callable(runner):
                    runner(_await_clip())
                else:
                    status.value = "الصق النص يدوياً داخل الحقل"
                    status.color = ft.Colors.ORANGE
                    page.update()
                return
            qr_field.value = str(value or "")
            status.value = "تم لصق نص الربط من الحافظة"
            status.color = ft.Colors.GREEN
            page.update()
        except Exception as ex:
            status.value = f"تعذر قراءة الحافظة: {ex}"
            status.color = ft.Colors.RED
            page.update()

    def scan_camera(ev):
        """Attempt to use any Flet scanner service/control if the runtime exposes it."""
        scanner_cls = getattr(ft, "BarcodeScanner", None) or getattr(ft, "QrScanner", None) or getattr(ft, "QRScanner", None)
        if scanner_cls is None:
            status.value = "ماسح الكاميرا غير مضمّن في نسخة Flet الحالية. استخدم لصق نص الربط كخيار احتياطي."
            status.color = ft.Colors.ORANGE
            page.update()
            return

        def on_result(result):
            try:
                text = getattr(result, "value", None) or getattr(result, "data", None) or getattr(result, "text", None) or str(result or "")
                qr_field.value = text
                status.value = "تم مسح QR. اضغط ربط وحفظ للتأكيد."
                status.color = ft.Colors.GREEN
                page.update()
            except Exception as ex:
                status.value = f"تعذر قراءة نتيجة المسح: {ex}"
                status.color = ft.Colors.RED
                page.update()

        try:
            try:
                scanner = scanner_cls(on_result=on_result)
            except TypeError:
                scanner = scanner_cls()
                try:
                    scanner.on_result = on_result
                except Exception:
                    pass
            try:
                if scanner not in page.overlay:
                    page.overlay.append(scanner)
            except Exception:
                pass
            for method_name in ("scan", "start_scan", "open", "show"):
                method = getattr(scanner, method_name, None)
                if callable(method):
                    method()
                    page.update()
                    return
            status.value = "تم العثور على ماسح QR لكن لم تُعرف طريقة تشغيله في نسخة Flet هذه. استخدم اللصق."
            status.color = ft.Colors.ORANGE
            page.update()
        except Exception as ex:
            status.value = f"تعذر فتح الكاميرا: {ex}"
            status.color = ft.Colors.RED
            page.update()

    apply_btn.on_click = do_pair

    camera_btn = ft.FilledButton(
        content=ft.Row([ft.Icon(ft.Icons.CAMERA_ALT), ft.Text("مسح بالكاميرا")], alignment=ft.MainAxisAlignment.CENTER),
        bgcolor=ft.Colors.TEAL,
        color=ft.Colors.WHITE,
        on_click=scan_camera,
    )
    paste_btn = ft.OutlinedButton(
        content=ft.Row([ft.Icon(ft.Icons.CONTENT_PASTE), ft.Text("لصق من الحافظة")], alignment=ft.MainAxisAlignment.CENTER),
        on_click=paste_clipboard,
    )

    dlg = ft.AlertDialog(
        modal=True,
        title=ft.Text("ربط Android مع Windows عبر QR", weight=ft.FontWeight.BOLD),
        content=ft.Container(
            width=430,
            content=ft.Column([
                info_banner("الربط لا يمنح صلاحيات دخول. بعد نجاح الربط ستسجل الدخول باسم المستخدم وكلمة المرور.", icon=ft.Icons.QR_CODE_SCANNER),
                camera_btn,
                ft.Text("أو استخدم النص الاحتياطي", size=12, color=ft.Colors.GREY_600, text_align=ft.TextAlign.CENTER),
                qr_field,
                paste_btn,
                status,
            ], tight=True, spacing=12),
        ),
        actions=[apply_btn, ft.TextButton("إلغاء", on_click=lambda ev: close_control(page, dlg))],
        actions_alignment=ft.MainAxisAlignment.END,
    )
    open_control(page, dlg)
    return dlg
