# -*- coding: utf-8 -*-
"""Reusable Android/Windows QR pairing dialog.

Flet's QR/camera scanner availability varies by runtime/build.  This dialog is
camera-ready when a scanner control exists, and always provides a paste fallback
for the QR payload generated by Windows.
"""
from __future__ import annotations

import inspect
import flet as ft
from views.flet_compat import open_control, close_control, run_async_task
from views.ui_kit import info_banner, show_snackbar, PRIMARY, PRIMARY_SOFT


def _payload_server_url(payload: str) -> str:
    try:
        from services.pairing_service import MobilePairingService
        data = MobilePairingService.parse_qr_text(payload)
        return str(data.get("server_url") or "")
    except Exception:
        return ""


def _format_payload_summary(payload: str) -> str:
    try:
        from services.pairing_service import MobilePairingService
        data = MobilePairingService.parse_qr_text(payload)
        server_url = str(data.get("server_url") or "—")
        expires_at = str(data.get("expires_at") or "—")
        contract = str(data.get("currency_contract") or "—")
        token = str(data.get("pairing_token") or "")
        token_hint = (token[:6] + "…" + token[-4:]) if len(token) > 12 else (token or "—")
        return f"الخادم: {server_url}\nينتهي: {expires_at}\nالعقد: {contract}\nرمز مؤقت: {token_hint}"
    except Exception:
        return ""


def _friendly_error(payload: str, exc: Exception) -> str:
    try:
        from services.network_diagnostics_service import classify_connection_error
        hint = classify_connection_error(_payload_server_url(payload), exc)
        return f"❌ {hint.title}: {hint.message}"
    except Exception:
        return f"❌ فشل الربط: {exc}"


def _set_button_loading(button, text: str, loading: bool = True):
    try:
        button.disabled = loading
        if loading:
            button.content = ft.Row([ft.ProgressRing(width=16, height=16), ft.Text(text)], alignment=ft.MainAxisAlignment.CENTER)
    except Exception:
        pass


def open_qr_pairing_dialog(page: ft.Page, *, on_success=None, initial_text: str = ""):
    qr_field = ft.TextField(
        label="نص QR / رمز الربط",
        hint_text="الصق نص الربط الذي يولده Windows أو امسح QR بالكاميرا",
        value=initial_text or "",
        multiline=True,
        min_lines=3,
        max_lines=4,
        border_radius=14,
        text_size=11,
        text_align=ft.TextAlign.LEFT,
        rtl=False,
    )
    summary_text = ft.Text("", size=11, color=ft.Colors.BLUE_GREY_700, text_align=ft.TextAlign.RIGHT)
    summary_box = ft.Container(
        visible=False,
        bgcolor=ft.Colors.BLUE_GREY_50,
        border_radius=10,
        padding=10,
        content=summary_text,
    )
    status = ft.Text("", size=12, color=ft.Colors.GREY_600, text_align=ft.TextAlign.CENTER)
    try:
        from database.connection import DatabaseConnection
        default_server_url = DatabaseConnection().server_url or ""
    except Exception:
        default_server_url = ""
    manual_server_field = ft.TextField(
        label="عنوان الخادم",
        hint_text="http://192.168.1.100:8000",
        value=default_server_url,
        text_align=ft.TextAlign.LEFT,
        rtl=False,
        text_size=12,
    )
    manual_code_field = ft.TextField(
        label="رمز الربط اليدوي",
        hint_text="مثال: 482913",
        text_align=ft.TextAlign.CENTER,
        rtl=False,
        text_size=18,
        keyboard_type=ft.KeyboardType.NUMBER,
    )

    def refresh_summary(ev=None):
        text = qr_field.value or ""
        summary = _format_payload_summary(text) if text.strip() else ""
        summary_text.value = summary
        summary_box.visible = bool(summary)
        try:
            page.update()
        except Exception:
            pass

    qr_field.on_change = refresh_summary

    apply_btn = ft.FilledButton(
        content=ft.Row([ft.Icon(ft.Icons.LINK), ft.Text("ربط وحفظ")], alignment=ft.MainAxisAlignment.CENTER),
        bgcolor=PRIMARY,
        color=ft.Colors.WHITE,
    )

    def _apply_payload(payload: str):
        try:
            if not payload or not payload.strip():
                status.value = "الصق نص الربط أو امسح QR أولاً"
                status.color = ft.Colors.RED
                page.update()
                return
            _set_button_loading(apply_btn, "جاري الربط", True)
            status.value = "جاري فحص الخادم ورمز الربط..."
            status.color = PRIMARY
            page.update()
            from services.pairing_service import MobilePairingService
            result = MobilePairingService.pair_from_qr_text(payload)
            if not result.ok:
                status.value = result.message
                status.color = ft.Colors.RED
                return
            status.value = f"✅ {result.message}\n{result.server_name} — {result.server_url}"
            status.color = ft.Colors.GREEN
            show_snackbar(page, "تم ربط الهاتف بالخادم. سجّل الدخول بحسابك.", False)
            if callable(on_success):
                on_success(result)
            close_control(page, dlg)
        except Exception as ex:
            status.value = _friendly_error(payload, ex)
            status.color = ft.Colors.RED
        finally:
            try:
                apply_btn.disabled = False
                apply_btn.content = ft.Row([ft.Icon(ft.Icons.LINK), ft.Text("ربط وحفظ")], alignment=ft.MainAxisAlignment.CENTER)
                page.update()
            except Exception:
                pass

    def do_pair(ev):
        _apply_payload(qr_field.value or "")

    def do_pair_code(ev):
        try:
            server_url = manual_server_field.value or ""
            code = manual_code_field.value or ""
            if not server_url.strip() or not code.strip():
                status.value = "أدخل عنوان الخادم ورمز الربط اليدوي"
                status.color = ft.Colors.RED
                page.update()
                return
            _set_button_loading(code_pair_btn, "جاري الربط", True)
            status.value = "جاري فحص الخادم والرمز اليدوي..."
            status.color = PRIMARY
            page.update()
            from services.pairing_service import MobilePairingService
            result = MobilePairingService.pair_with_code(server_url, code)
            if not result.ok:
                status.value = result.message
                status.color = ft.Colors.RED
                return
            status.value = f"✅ {result.message}\n{result.server_name} — {result.server_url}"
            status.color = ft.Colors.GREEN
            show_snackbar(page, "تم ربط الهاتف بالخادم. سجّل الدخول بحسابك.", False)
            if callable(on_success):
                on_success(result)
            close_control(page, dlg)
        except Exception as ex:
            status.value = _friendly_error(server_url, ex)
            status.color = ft.Colors.RED
        finally:
            try:
                code_pair_btn.disabled = False
                code_pair_btn.content = ft.Row([ft.Icon(ft.Icons.PIN), ft.Text("ربط بالرمز اليدوي")], alignment=ft.MainAxisAlignment.CENTER)
                page.update()
            except Exception:
                pass

    def paste_clipboard(ev):
        try:
            getter = getattr(page, "get_clipboard", None)
            if not callable(getter):
                status.value = "هذه نسخة Flet لا توفر قراءة الحافظة. الصق النص يدوياً."
                status.color = ft.Colors.ORANGE
                page.update()
                return
            value = getter()
            if inspect.iscoroutine(value):
                async def _await_clip():
                    try:
                        text = await value
                        qr_field.value = str(text or "")
                        status.value = "تم لصق نص الربط من الحافظة"
                        status.color = ft.Colors.GREEN
                        refresh_summary()
                        page.update()
                    except Exception as ex:
                        status.value = f"تعذر قراءة الحافظة: {ex}"
                        status.color = ft.Colors.RED
                        page.update()
                run_async_task(page, _await_clip)
                return
            qr_field.value = str(value or "")
            status.value = "تم لصق نص الربط من الحافظة"
            status.color = ft.Colors.GREEN
            refresh_summary()
            page.update()
        except Exception as ex:
            status.value = f"تعذر قراءة الحافظة: {ex}"
            status.color = ft.Colors.RED
            page.update()

    def scan_camera(ev):
        """Attempt to use any Flet scanner service/control if the runtime exposes it."""
        try:
            from services.camera_permission_service import CameraPermissionService
            ok, message = CameraPermissionService.request(page)
            if not ok:
                status.value = message
                status.color = ft.Colors.RED
                page.update()
                return
            if message:
                status.value = message
                status.color = ft.Colors.GREY_600
                page.update()
        except Exception:
            pass
        scanner_cls = getattr(ft, "BarcodeScanner", None) or getattr(ft, "QrScanner", None) or getattr(ft, "QRScanner", None)
        if scanner_cls is None:
            status.value = "صلاحية الكاميرا لا تكفي وحدها: نسخة Flet الحالية لا تحتوي قارئ QR مدمج. استخدم لصق نص الربط، أو ابنِ نسخة تحتوي QR scanner extension."
            status.color = ft.Colors.ORANGE
            page.update()
            return

        def on_result(result):
            try:
                text = getattr(result, "value", None) or getattr(result, "data", None) or getattr(result, "text", None) or str(result or "")
                qr_field.value = text
                status.value = "تم مسح QR. اضغط ربط وحفظ للتأكيد."
                status.color = ft.Colors.GREEN
                refresh_summary()
                page.update()
            except Exception as ex:
                status.value = f"تعذر قراءة نتيجة المسح: {ex}"
                status.color = ft.Colors.RED
                page.update()

        try:
            try:
                scanner = scanner_cls(on_result=on_result)
            except TypeError:
                scanner = scanner_cls()
                try:
                    scanner.on_result = on_result
                except Exception:
                    pass
            try:
                if scanner not in page.overlay:
                    page.overlay.append(scanner)
            except Exception:
                pass
            for method_name in ("scan", "start_scan", "open", "show"):
                method = getattr(scanner, method_name, None)
                if callable(method):
                    method()
                    page.update()
                    return
            status.value = "تم العثور على ماسح QR لكن لم تُعرف طريقة تشغيله في نسخة Flet هذه. استخدم اللصق."
            status.color = ft.Colors.ORANGE
            page.update()
        except Exception as ex:
            status.value = f"تعذر فتح الكاميرا: {ex}"
            status.color = ft.Colors.RED
            page.update()

    apply_btn.on_click = do_pair

    camera_btn = ft.FilledButton(
        content=ft.Row([ft.Icon(ft.Icons.CAMERA_ALT), ft.Text("مسح بالكاميرا")], alignment=ft.MainAxisAlignment.CENTER),
        bgcolor=ft.Colors.TEAL,
        color=ft.Colors.WHITE,
        on_click=scan_camera,
    )
    paste_btn = ft.OutlinedButton(
        content=ft.Row([ft.Icon(ft.Icons.CONTENT_PASTE), ft.Text("لصق من الحافظة")], alignment=ft.MainAxisAlignment.CENTER),
        on_click=paste_clipboard,
    )
    code_pair_btn = ft.OutlinedButton(
        content=ft.Row([ft.Icon(ft.Icons.PIN), ft.Text("ربط بالرمز اليدوي")], alignment=ft.MainAxisAlignment.CENTER),
        on_click=do_pair_code,
    )

    dlg = ft.AlertDialog(
        modal=True,
        title=ft.Text("ربط Android مع Windows عبر QR", weight=ft.FontWeight.BOLD),
        content=ft.Container(
            width=430,
            content=ft.Column([
                info_banner("الربط لا يمنح صلاحيات دخول. بعد نجاح الربط ستسجل الدخول باسم المستخدم وكلمة المرور.", icon=ft.Icons.QR_CODE_SCANNER),
                camera_btn,
                ft.Text("أو استخدم النص الاحتياطي", size=12, color=ft.Colors.GREY_600, text_align=ft.TextAlign.CENTER),
                qr_field,
                summary_box,
                paste_btn,
                ft.Divider(),
                ft.Text("أو أدخل عنوان الخادم والرمز القصير الظاهر في Windows", size=11, color=ft.Colors.GREY_600, text_align=ft.TextAlign.CENTER),
                manual_server_field,
                manual_code_field,
                code_pair_btn,
                status,
            ], tight=True, spacing=12),
        ),
        actions=[apply_btn, ft.TextButton("إلغاء", on_click=lambda ev: close_control(page, dlg))],
        actions_alignment=ft.MainAxisAlignment.END,
    )
    open_control(page, dlg)
    return dlg
