# -*- coding: utf-8 -*-
"""Data-source contracts for Hawaa Accounting.

The UI and repositories should not decide whether data comes from SQLite or
from the REST server. This module defines the minimal contract used by the
current repositories. More methods can be moved here incrementally without
breaking old compatibility methods on DatabaseConnection.
"""
from __future__ import annotations

from typing import Dict, List, Optional, Protocol, Any


class DataSource(Protocol):
    def is_remote(self) -> bool: ...

    def execute(self, sql: str, params=(), audit_data=None): ...
    def executemany(self, sql: str, params_list, audit_data=None): ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def begin(self) -> None: ...

    def get_expenses(self) -> List[Dict[str, Any]]: ...
    def add_expense(self, data: Dict[str, Any]) -> int: ...
    def update_expense(self, expense_id: int, data: Dict[str, Any]) -> None: ...
    def delete_expense(self, expense_id: int) -> None: ...

    def get_users(self) -> List[Dict[str, Any]]: ...
    def add_user(self, data: Dict[str, Any]) -> int: ...

    def get_audit_log(self) -> List[Dict[str, Any]]: ...

    def get_setting(self, key: str, default: Optional[Any] = None): ...
    def set_setting(self, key: str, value: str) -> None: ...

    def get_all_currencies(self) -> List[Dict[str, Any]]: ...
    def update_exchange_rate(self, currency_code: str, rate_to_usd: float) -> None: ...
    def get_exchange_rate_history(self) -> List[Dict[str, Any]]: ...
